######################################################################
# Automatically generated by qmake (3.0) Wed Jan 11 21:45:47 2017
######################################################################

QT+=widgets
INCLUDEPATH+=/usr/include/python2.7/
INCLUDEPATH+=../..
INCLUDEPATH+=./Gui
INCLUDEPATH+=..
INCLUDEPATH+=./Spreadsheet
CONFIG+=c++14
QT+=xml
QT+=printsupport
QT+=uitools
QT+=network
QT+=opengl
QT+=svg
TEMPLATE = app
TARGET = Gui
INCLUDEPATH += .

# Input
HEADERS += LineEdit.h \
           PreCompiled.h \
           PropertiesDialog.h \
           qtcolorpicker.h \
           SheetModel.h \
           SheetTableView.h \
           SpreadsheetDelegate.h \
           SpreadsheetView.h \
           ui_PropertiesDialog.h \
           ui_Sheet.h \
           ViewProviderSpreadsheet.h \
           Workbench.h
FORMS += PropertiesDialog.ui Sheet.ui
SOURCES += AppSpreadsheetGui.cpp \
           Command.cpp \
           LineEdit.cpp \
           PreCompiled.cpp \
           PropertiesDialog.cpp \
           qtcolorpicker.cpp \
           SheetModel.cpp \
           SheetTableView.cpp \
           SpreadsheetDelegate.cpp \
           SpreadsheetView.cpp \
           ViewProviderSpreadsheet.cpp \
           Workbench.cpp
RESOURCES += Resources/Spreadsheet.qrc
TRANSLATIONS += Resources/translations/Spreadsheet.ts \
                Resources/translations/Spreadsheet_af.ts \
                Resources/translations/Spreadsheet_cs.ts \
                Resources/translations/Spreadsheet_de.ts \
                Resources/translations/Spreadsheet_el.ts \
                Resources/translations/Spreadsheet_es-ES.ts \
                Resources/translations/Spreadsheet_fi.ts \
                Resources/translations/Spreadsheet_fr.ts \
                Resources/translations/Spreadsheet_hr.ts \
                Resources/translations/Spreadsheet_hu.ts \
                Resources/translations/Spreadsheet_it.ts \
                Resources/translations/Spreadsheet_ja.ts \
                Resources/translations/Spreadsheet_nl.ts \
                Resources/translations/Spreadsheet_no.ts \
                Resources/translations/Spreadsheet_pl.ts \
                Resources/translations/Spreadsheet_pt-BR.ts \
                Resources/translations/Spreadsheet_pt-PT.ts \
                Resources/translations/Spreadsheet_ro.ts \
                Resources/translations/Spreadsheet_ru.ts \
                Resources/translations/Spreadsheet_sk.ts \
                Resources/translations/Spreadsheet_sl.ts \
                Resources/translations/Spreadsheet_sr.ts \
                Resources/translations/Spreadsheet_sv-SE.ts \
                Resources/translations/Spreadsheet_tr.ts \
                Resources/translations/Spreadsheet_uk.ts \
                Resources/translations/Spreadsheet_zh-CN.ts \
                Resources/translations/Spreadsheet_zh-TW.ts
