######################################################################
# Automatically generated by qmake (3.0) Sat Jan 7 11:19:45 2017
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = testwaitcursor
INCLUDEPATH += .

# Input
HEADERS += FCConfig.h mainwindow.h ui_mainwindow.h WaitCursor.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp WaitCursor.cpp
